name: auth_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ./packages/ui_kit
  db:
    path: ./packages/db
  dio: ^5.8.0+1
  go_router: ^16.0.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  l: ^5.0.1
  drift: ^2.28.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  flashy_flushbar: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.1.0
  build_runner: 2.4.15

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
     - family: WorkSans
       fonts:
         - asset: assets/fonts/WorkSans-Bold.ttf
           weight: 700
         - asset: assets/fonts/WorkSans-Medium.ttf
           weight: 500
         - asset: assets/fonts/WorkSans-Regular.ttf
           weight: 400
         - asset: assets/fonts/WorkSans-SemiBold.ttf
           weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mivo.png"
  min_sdk_android: 21
